version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ad
      - APP_SECRET_KEY=ashleshshenoy
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  mongo-data:
